services:
  - type: web
    name: cantina-go-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: back
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false

  - type: web
    name: cantina-go-frontend
    env: static
    rootDir: front
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://cantina-go-415n.onrender.com
